endpoints:
    prometheus:
        sensitive: false
micronaut:
    application:
        name: complete
    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
